version: '3.5'
networks:
  default:
    external: true
    name: app-mysql

services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mhdb
    ports:
      - 3308:3306

  app:
    image: eugenevdovin/marvelheroestestproject:mhtestappfinal
    depends_on:
      - mysqldb
    ports:
      - 9090:8080
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb/mhdb?useSSL=false&allowPublicKeyRetrieval=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "root",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'